<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>apuntes_csharp</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  

    <AssemblyName>apuntes_csharp</AssemblyName>
    <RootNamespace>apuntes_csharp</RootNamespace>
    <Version>1.0.0</Version>
    <Description>Proyecto de inventario</Description>
  </PropertyGroup>

</Project>
